/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author YEAC
 */
public class frm_detail_transaksi_cicil extends javax.swing.JFrame {
    koneksi dbsetting;
    String driver,database,user,pass,tgl;
    Object tabel;
    /**
     * Creates new form frm_detail_transaksi_cicil
     */
    public frm_detail_transaksi_cicil() {
        initComponents();
        txt_sisa.setVisible(false);
        ImageIcon ico = new ImageIcon("src/images/usuarios.png");
        setIconImage(ico.getImage());
        Dimension ss = Toolkit.getDefaultToolkit ().getScreenSize ();
        Dimension frameSize = new Dimension ( 850, 375 );
        this.setBounds ( ss.width / 2 - frameSize.width / 2, 
                  ss.height / 2 - frameSize.height / 2,
                  frameSize.width, frameSize.height );
        //koneksi database
        dbsetting = new koneksi();
        driver = dbsetting.SettingPanel("DBDriver");
        database = dbsetting.SettingPanel("DBDatabase");
        user = dbsetting.SettingPanel("DBUsername");
        pass = dbsetting.SettingPanel("DBPassword");
        tabel_detail_transaksi_cicil.setModel(tableModel);
        settableload();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_detail_transaksi_cicil = new javax.swing.JTable();
        btn_ubah = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        carii = new javax.swing.JComboBox();
        cari = new javax.swing.JTextField();
        go = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_kode_pembeli = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_tanggal_pembeli = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_nama_pembeli = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_uang_muka = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_tenggang_waktu = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_ket = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txt_sisa = new javax.swing.JTextField();
        pembuat1 = new Form.pembuat();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Form Detail Transaksi Cicil");
        setAutoRequestFocus(false);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setFocusable(false);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel_detail_transaksi_cicil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Pembeli", "Tanggal Pembeli", "Nama Pembeli", "Alamat Pembeli", "Nama Barang", "Harga Satuan", "Jumlah Beli", "Uang Muka"
            }
        ));
        tabel_detail_transaksi_cicil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_detail_transaksi_cicilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_detail_transaksi_cicil);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 199, 810, 97));

        btn_ubah.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit_editor_pen_pencil_write-16 - Copy.png"))); // NOI18N
        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 302, -1, -1));

        btn_keluar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/oneline_home-16 (1).png"))); // NOI18N
        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 302, 90, -1));

        btn_batal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/alert.png"))); // NOI18N
        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });
        getContentPane().add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 302, -1, -1));

        carii.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cari Berdasarkan", "Kode Pembeli", "Nama Pembeli", "Tanggal Pembelian" }));
        carii.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cariiMouseClicked(evt);
            }
        });
        carii.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariiActionPerformed(evt);
            }
        });
        getContentPane().add(carii, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 165, 130, -1));

        cari.setEnabled(false);
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 165, 126, -1));

        go.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-ico.png"))); // NOI18N
        go.setText("Cari");
        go.setEnabled(false);
        go.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goMouseClicked(evt);
            }
        });
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });
        getContentPane().add(go, new org.netbeans.lib.awtextra.AbsoluteConstraints(746, 163, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Kode Pembeli");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 3, -1, -1));

        txt_kode_pembeli.setEditable(false);
        getContentPane().add(txt_kode_pembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 0, 112, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tanggal Pembeli");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 34, -1, -1));

        txt_tanggal_pembeli.setEditable(false);
        getContentPane().add(txt_tanggal_pembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 31, 114, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama Pembeli");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 66, -1, -1));

        txt_nama_pembeli.setEditable(false);
        txt_nama_pembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nama_pembeliActionPerformed(evt);
            }
        });
        txt_nama_pembeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nama_pembeliKeyTyped(evt);
            }
        });
        getContentPane().add(txt_nama_pembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 63, 166, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Uang Muka");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 97, -1, -1));

        txt_uang_muka.setEditable(false);
        txt_uang_muka.setToolTipText("Isi Menggunakan Angka !");
        txt_uang_muka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_uang_mukaActionPerformed(evt);
            }
        });
        txt_uang_muka.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_uang_mukaKeyTyped(evt);
            }
        });
        getContentPane().add(txt_uang_muka, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 94, 113, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tenggang Waktu");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, -1, -1));

        txt_tenggang_waktu.setEditable(false);
        txt_tenggang_waktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tenggang_waktuActionPerformed(evt);
            }
        });
        getContentPane().add(txt_tenggang_waktu, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 120, 113, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Keterangan");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 151, -1, -1));

        txt_ket.setEditable(false);
        txt_ket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ketActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ket, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 148, 114, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reload-16.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 146, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1469624709_22.png"))); // NOI18N
        jButton1.setText("Cetak");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 146, -1, -1));

        txt_sisa.setEditable(false);
        txt_sisa.setEnabled(false);
        getContentPane().add(txt_sisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 81, -1, -1));

        javax.swing.GroupLayout pembuat1Layout = new javax.swing.GroupLayout(pembuat1);
        pembuat1.setLayout(pembuat1Layout);
        pembuat1Layout.setHorizontalGroup(
            pembuat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        pembuat1Layout.setVerticalGroup(
            pembuat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        getContentPane().add(pembuat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == btn_keluar){
            int a;
            a = JOptionPane.showConfirmDialog(null, "ANDA YAKIN AKAN KELUAR?", "WARNING!", JOptionPane.YES_NO_OPTION);
            
            if(a == JOptionPane.YES_OPTION){
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void cariiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cariiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cariiMouseClicked

    private void cariiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariiActionPerformed
        cari.setEnabled(true);
        go.setEnabled(true);
    }//GEN-LAST:event_cariiActionPerformed
public void carikodepembeli() {
    try {
        Class.forName(driver);
        Object row[] = {"Kode Pembeli",
                            "Tanggal Pembelian",
                            "Tenggang Waktu",
                            "Nama Pembeli",
                            "Alamat Pembeli",
                            "Nama Barang",
                            "Harga Satuan",
                            "Jumlah Beli ",
                            "Uang Muka",
                            "Keterangan"};
        tableModel = new DefaultTableModel(null,row);
        tabel_detail_transaksi_cicil.setModel(tableModel); 
        Connection kon = DriverManager.getConnection(database,user,pass);
        Statement stt = kon.createStatement();
        String sql = "SELECT\n" +
"    `tabel_detail_transaksi_cicil`.`nama_barang`\n" +
"    ,`tabel_detail_transaksi_cicil`.`alamat_pembeli`\n" +
"    , `tabel_detail_transaksi_cicil`.`banyak_barang`\n" +
"    , `tabel_detail_transaksi_cicil`.`harga_satuan`\n" +
"    , `tabel_transaksi_cicil`.`kode_pembeli_cicil`\n" +
"    , `tabel_transaksi_cicil`.`nama_pembeli`\n" +
"    , `tabel_transaksi_cicil`.`keterangan`\n" +
"    , `tabel_transaksi_cicil`.`tanggal_pembeli`\n" +
"    , `tabel_detail_transaksi_cicil`.`harga_total`\n" +
"    , `tabel_detail_transaksi_cicil`.`uang_muka`\n" +
"    , `tabel_detail_transaksi_cicil`.`sisa`\n" +
"    , `tabel_detail_transaksi_cicil`.`tenggang_waktu`\n" +
                
"FROM\n" +
"    `10114255_mebel`.`tabel_detail_transaksi_cicil`\n" +
"    INNER JOIN `10114255_mebel`.`tabel_transaksi_cicil` \n" +
"        ON (`tabel_detail_transaksi_cicil`.`kode_pembeli_cicil` = `tabel_transaksi_cicil`.`kode_pembeli_cicil`) where `tabel_transaksi_cicil`.`kode_pembeli_cicil`" + " like '%" + cari.getText() + "%'";
        ResultSet res = stt.executeQuery(sql);
        while (res.next()) {
            String a = res.getString(5);
            String b = res.getString(8);
            String c = res.getString(12);   
            String d = res.getString(6);
            String e = res.getString(2);
            String f = res.getString(1);
            String g = res.getString(4);
            String h = res.getString(3);
            String i = res.getString(10);
            String j = res.getString(7);
            String[] data = {a,b,c,d,e,f,g,h,i,j};
        tableModel.addRow(data);
            }
        }
        catch (SQLException ex) {
            Logger.getLogger(frm_barang.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_barang.class.getName()).log(Level.SEVERE, null, ex);
        }
}

public void carinamapembeli() {
    try {
        Class.forName(driver);
        Object row[] = {"Kode Pembeli",
                            "Tanggal Pembelian",
                            "Tenggang Waktu",
                            "Nama Pembeli",
                            "Alamat Pembeli",
                            "Nama Barang",
                            "Harga Satuan",
                            "Jumlah Beli ",
                            "Uang Muka",
                            "Keterangan"};
        tableModel = new DefaultTableModel(null,row);
        tabel_detail_transaksi_cicil.setModel(tableModel); 
        Connection kon = DriverManager.getConnection(database,user,pass);
        Statement stt = kon.createStatement();
        String sql = "SELECT\n" +
"    `tabel_detail_transaksi_cicil`.`nama_barang`\n" +
"    ,`tabel_detail_transaksi_cicil`.`alamat_pembeli`\n" +
"    , `tabel_detail_transaksi_cicil`.`banyak_barang`\n" +
"    , `tabel_detail_transaksi_cicil`.`harga_satuan`\n" +
"    , `tabel_transaksi_cicil`.`kode_pembeli_cicil`\n" +
"    , `tabel_transaksi_cicil`.`nama_pembeli`\n" +
"    , `tabel_transaksi_cicil`.`keterangan`\n" +
"    , `tabel_transaksi_cicil`.`tanggal_pembeli`\n" +
"    , `tabel_detail_transaksi_cicil`.`harga_total`\n" +
"    , `tabel_detail_transaksi_cicil`.`uang_muka`\n" +
"    , `tabel_detail_transaksi_cicil`.`sisa`\n" +
"    , `tabel_detail_transaksi_cicil`.`tenggang_waktu`\n" +
                
"FROM\n" +
"    `10114255_mebel`.`tabel_detail_transaksi_cicil`\n" +
"    INNER JOIN `10114255_mebel`.`tabel_transaksi_cicil` \n" +
"        ON (`tabel_detail_transaksi_cicil`.`kode_pembeli_cicil` = `tabel_transaksi_cicil`.`kode_pembeli_cicil`) where `tabel_transaksi_cicil`.`nama_pembeli`" + " like '%" + cari.getText() + "%'";
        ResultSet res = stt.executeQuery(sql);
        while (res.next()) {
            String a = res.getString(5);
            String b = res.getString(8);
            String c = res.getString(12);   
            String d = res.getString(6);
            String e = res.getString(2);
            String f = res.getString(1);
            String g = res.getString(4);
            String h = res.getString(3);
            String i = res.getString(10);
            String j = res.getString(7);
            String[] data = {a,b,c,d,e,f,g,h,i,j};
        tableModel.addRow(data);
            }
        }
        catch (SQLException ex) {
            Logger.getLogger(frm_barang.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_barang.class.getName()).log(Level.SEVERE, null, ex);
        }
}


public void caritanggalpembeli() {
    try {
        Class.forName(driver);
        Object row[] = {"Kode Pembeli",
                            "Tanggal Pembelian",
                            "Tenggang Waktu",
                            "Nama Pembeli",
                            "Alamat Pembeli",
                            "Nama Barang",
                            "Harga Satuan",
                            "Jumlah Beli ",
                            "Uang Muka",
                            "Keterangan"};
        tableModel = new DefaultTableModel(null,row);
        tabel_detail_transaksi_cicil.setModel(tableModel); 
        Connection kon = DriverManager.getConnection(database,user,pass);
        Statement stt = kon.createStatement();
        String sql = "SELECT\n" +
"    `tabel_detail_transaksi_cicil`.`nama_barang`\n" +
"    ,`tabel_detail_transaksi_cicil`.`alamat_pembeli`\n" +
"    , `tabel_detail_transaksi_cicil`.`banyak_barang`\n" +
"    , `tabel_detail_transaksi_cicil`.`harga_satuan`\n" +
"    , `tabel_transaksi_cicil`.`kode_pembeli_cicil`\n" +
"    , `tabel_transaksi_cicil`.`nama_pembeli`\n" +
"    , `tabel_transaksi_cicil`.`keterangan`\n" +
"    , `tabel_transaksi_cicil`.`tanggal_pembeli`\n" +
"    , `tabel_detail_transaksi_cicil`.`harga_total`\n" +
"    , `tabel_detail_transaksi_cicil`.`uang_muka`\n" +
"    , `tabel_detail_transaksi_cicil`.`sisa`\n" +
"    , `tabel_detail_transaksi_cicil`.`tenggang_waktu`\n" +
                
"FROM\n" +
"    `10114255_mebel`.`tabel_detail_transaksi_cicil`\n" +
"    INNER JOIN `10114255_mebel`.`tabel_transaksi_cicil` \n" +
"        ON (`tabel_detail_transaksi_cicil`.`kode_pembeli_cicil` = `tabel_transaksi_cicil`.`kode_pembeli_cicil`)where `tabel_transaksi_cicil`.`tanggal_pembeli`" + " like '%" + cari.getText() + "%'";
        ResultSet res = stt.executeQuery(sql);
        while (res.next()) {
            String a = res.getString(5);
            String b = res.getString(8);
            String c = res.getString(12);   
            String d = res.getString(6);
            String e = res.getString(2);
            String f = res.getString(1);
            String g = res.getString(4);
            String h = res.getString(3);
            String i = res.getString(10);
            String j = res.getString(7);
            String[] data = {a,b,c,d,e,f,g,h,i,j};
        tableModel.addRow(data);
            }
        }
        catch (SQLException ex) {
            Logger.getLogger(frm_barang.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_barang.class.getName()).log(Level.SEVERE, null, ex);
        }
}


    private void goMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goMouseClicked
        if(carii.getSelectedIndex() == 1){
            carikodepembeli();
        }

        if (carii.getSelectedIndex()== 2) {
            carinamapembeli();
        }
        if (carii.getSelectedIndex()== 3) {
            caritanggalpembeli();
        }
    }//GEN-LAST:event_goMouseClicked

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goActionPerformed

    private void txt_nama_pembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nama_pembeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nama_pembeliActionPerformed

    private void txt_uang_mukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_uang_mukaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_uang_mukaActionPerformed

    private void txt_tenggang_waktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tenggang_waktuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tenggang_waktuActionPerformed
int row = 0;
public void tampil_field()
{
    row = tabel_detail_transaksi_cicil.getSelectedRow();
    txt_kode_pembeli.setText(tableModel.getValueAt(row, 0).toString());
    txt_tanggal_pembeli.setText(tableModel.getValueAt(row, 1).toString());
    txt_nama_pembeli.setText(tableModel.getValueAt(row, 3).toString());
    txt_uang_muka.setText(tableModel.getValueAt(row, 8).toString());
    txt_tenggang_waktu.setText(tableModel.getValueAt(row, 2).toString());
    txt_ket.setText(tableModel.getValueAt(row, 9).toString());
    btn_ubah.setEnabled(true);  
}
    private void tabel_detail_transaksi_cicilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_detail_transaksi_cicilMouseClicked
        // TODO add your handling code here:
         if(evt.getClickCount()==1)
        {
            tampil_field();
        }
        btn_ubah.setEnabled(true); 
    }//GEN-LAST:event_tabel_detail_transaksi_cicilMouseClicked

    private void txt_ketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ketActionPerformed
public void update_keterangan() throws SQLException{
        try {
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database,user,pass);
            Statement stt = kon.createStatement();
            stt.executeUpdate("update tabel_transaksi_cicil set kode_pembeli_cicil='"+txt_kode_pembeli.getText()+"',"+
     "keterangan='"+txt_ket.getText()+"'where kode_pembeli_cicil ='"+txt_kode_pembeli.getText()+"'");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_detail_transaksi_cicil.class.getName()).log(Level.SEVERE, null, ex);
        }  
}
public void update_sisa() throws SQLException{
        try {
            Class.forName(driver);
            Connection kon = DriverManager.getConnection(database,user,pass);
            Statement stt = kon.createStatement();
            stt.executeUpdate("update tabel_detail_transaksi_cicil set kode_pembeli_cicil='"+txt_kode_pembeli.getText()+"',"+
     "sisa='"+txt_sisa.getText()+"'where kode_pembeli_cicil ='"+txt_kode_pembeli.getText()+"'");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frm_detail_transaksi_cicil.class.getName()).log(Level.SEVERE, null, ex);
        }  
}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       txt_ket.setText("Lunas");
       txt_sisa.setText("Lunas");
    }//GEN-LAST:event_jButton2ActionPerformed
public void membersihkan_tabel(){
    while(tableModel.getRowCount()>0){
        for(int i=0;i<tableModel.getRowCount();i++){
            tableModel.removeRow(i);
        }
    }
}
    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
            if(evt.getSource() == btn_ubah){
            int a;
            a = JOptionPane.showConfirmDialog(null, "ANDA YAKIN PELANGGAN SUDAH MELUNASI BIAYA?", "WARNING!", JOptionPane.YES_NO_OPTION);
            
            if(a == JOptionPane.YES_OPTION){
            try {
            // TODO add your handling code here:
            update_keterangan();
            update_sisa();
            membersihkan_tabel();
            settableload();
            JOptionPane.showMessageDialog(null, "Berhasil Tersimpan!");
        } catch (SQLException ex) {
            Logger.getLogger(frm_detail_transaksi_cicil.class.getName()).log(Level.SEVERE, null, ex);
        }
            }
        }

    }//GEN-LAST:event_btn_ubahActionPerformed
 public void runReportDefault(String sourcefilename, HashMap hash) {
        try {
             Class.forName(driver);
             Connection kon = DriverManager.getConnection(database,user,pass); 
            InputStream report;
            report = getClass().getResourceAsStream(sourcefilename);
            JasperPrint jprint = JasperFillManager.fillReport(report,hash, kon);
            JasperViewer viewer = new JasperViewer(jprint, false);
            viewer.setFitPageZoomRatio();
            viewer.setVisible(true);
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            String NamaFile = "/report/report_transaksi_cicil.jasper";
            HashMap hash = new HashMap();
        try {
            hash.put("kodepembelicicil", txt_kode_pembeli.getText());
            runReportDefault(NamaFile,hash);
        } catch (Exception e) {
        }       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_nama_pembeliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nama_pembeliKeyTyped
        // TODO add your handling code here:
        if (txt_nama_pembeli.getText().length() == 15 ) {
        evt.consume();
        
    }
    }//GEN-LAST:event_txt_nama_pembeliKeyTyped

    private void txt_uang_mukaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_uang_mukaKeyTyped
        // TODO add your handling code here:
        if (txt_uang_muka.getText().length() == 8 ) {
        evt.consume();
    }
    }//GEN-LAST:event_txt_uang_mukaKeyTyped
public void membersihkan_teks(){
    txt_kode_pembeli.setText("");
    txt_tanggal_pembeli.setText("");
    txt_nama_pembeli.setText("");
    txt_uang_muka.setText("");
    txt_tenggang_waktu.setText("");
    txt_ket.setText("");

}
    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        membersihkan_teks();
    }//GEN-LAST:event_btn_batalActionPerformed
private javax.swing.table.DefaultTableModel tableModel = getDefaultTabelModel();
private javax.swing.table.DefaultTableModel getDefaultTabelModel()
{
    //membuat judul header
    return new javax.swing.table.DefaultTableModel
            (
                new  Object[][] {},
                new String[]{"Kode Pembeli",
                            "Tanggal Pembelian",
                            "Tenggang Waktu",
                            "Nama Pembeli",
                            "Alamat Pembeli",
                            "Nama Barang",
                            "Harga Satuan",
                            "Jumlah Beli ",
                            "Uang Muka",
                            "Keterangan"}
            )
    //disable perubahan pada grid
    {
        boolean[] canEdit = new boolean[]
        {
            false, false, false, false, false
        };
        
        public boolean isCellEdittable(int  rowIndex, int columnIndex)
        {
            return canEdit[columnIndex];
        }
    };
}
String data[] = new String[10];
private void settableload()
{
    String stat = "";
    try
    {
        Class.forName(driver);
        Connection kon = DriverManager.getConnection(database,user,pass);
        Statement stt = kon.createStatement();
        String SQL ="SELECT\n" +
"    `tabel_detail_transaksi_cicil`.`nama_barang`\n" +
"    ,`tabel_detail_transaksi_cicil`.`alamat_pembeli`\n" +
"    , `tabel_detail_transaksi_cicil`.`banyak_barang`\n" +
"    , `tabel_detail_transaksi_cicil`.`harga_satuan`\n" +
"    , `tabel_transaksi_cicil`.`kode_pembeli_cicil`\n" +
"    , `tabel_transaksi_cicil`.`nama_pembeli`\n" +
"    , `tabel_transaksi_cicil`.`keterangan`\n" +
"    , `tabel_transaksi_cicil`.`tanggal_pembeli`\n" +
"    , `tabel_detail_transaksi_cicil`.`harga_total`\n" +
"    , `tabel_detail_transaksi_cicil`.`uang_muka`\n" +
"    , `tabel_detail_transaksi_cicil`.`sisa`\n" +
"    , `tabel_detail_transaksi_cicil`.`tenggang_waktu`\n" +
                
"FROM\n" +
"    `10114255_mebel`.`tabel_detail_transaksi_cicil`\n" +
"    INNER JOIN `10114255_mebel`.`tabel_transaksi_cicil` \n" +
"        ON (`tabel_detail_transaksi_cicil`.`kode_pembeli_cicil` = `tabel_transaksi_cicil`.`kode_pembeli_cicil`) GROUP BY kode_pembeli_cicil";
        ResultSet res = stt.executeQuery(SQL);
        while (res.next()) 
        {
           data[0] = res.getString(5);//kode
           data[1] = res.getString(8);//tanggal beli
           data[2] = res.getString(12);//tenggang waktu
           data[3] = res.getString(6);//nama
           data[4] = res.getString(2);//alamat
           data[5] = res.getString(1);//nama barang
           data[6] = res.getString(4);//harga satuan
           data[7] = res.getString(3);//jumalah beli
           data[8] = res.getString(10);//uang muka
           data[9] = res.getString(7);//nama pembeli
           tableModel.addRow(data);
        }
        res.close();
        stt.close();
        kon.close();
    }
    catch(Exception ex)
    {
        System.err.println(ex.getMessage());
        JOptionPane.showMessageDialog(null, ex.getMessage(),"Error",JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_detail_transaksi_cicil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_detail_transaksi_cicil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_detail_transaksi_cicil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_detail_transaksi_cicil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_detail_transaksi_cicil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JTextField cari;
    private javax.swing.JComboBox carii;
    private javax.swing.JButton go;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private Form.pembuat pembuat1;
    private javax.swing.JTable tabel_detail_transaksi_cicil;
    private javax.swing.JTextField txt_ket;
    private javax.swing.JTextField txt_kode_pembeli;
    private javax.swing.JTextField txt_nama_pembeli;
    private javax.swing.JTextField txt_sisa;
    private javax.swing.JTextField txt_tanggal_pembeli;
    private javax.swing.JTextField txt_tenggang_waktu;
    private javax.swing.JTextField txt_uang_muka;
    // End of variables declaration//GEN-END:variables
}
